name: test-snapd-swtpm
version: 0.1.0
summary: Libtpms-based TPM emulator
description: |
  Libtpms-based TPM emulator with socket, character device, and Linux
  CUSE interface.
base: core20
architectures:
  - build-on: amd64

grade: stable
confinement: strict

# TODO: enable content interface for sharing the swtpm socket for other strict
# snaps to consume
# slots:
#   swtpm-socket:
#     interface: content
#     conent: swtpm-socket
#     read:
#       - $SNAP_DATA/swtpm-sock

apps:
  swtpm:
    command: usr/bin/swtpm
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/swtpm/:$SNAP/usr/local/lib/
    plugs:
      - network-bind
  swtpm-sock:
    command: usr/bin/swtpm socket --tpmstate $TPMDIR --tpm2 --ctrl $CTRL
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - home
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/swtpm/:$SNAP/usr/local/lib/
      TPMDIR: dir=$SNAP_DATA
      CTRL: type=unixio,path=$SNAP_DATA/swtpm-sock

  # TODO: when user daemons are not experimental add this so one can use swtpm
  # with qemu as non-root user, otherwise one can't install this snap w/o
  # enabling experimental user daemon support
  # swtpm-sock-user:
  #   command: usr/bin/swtpm socket --tpmstate $TPMDIR --tpm2 --ctrl $CTRL
  #   daemon: simple
  #   passthrough:
  #     daemon-scope: user
  #   restart-condition: always
  #   plugs:
  #     - network-bind
  #     - home
  #   environment:
  #     LD_LIBRARY_PATH: $SNAP/usr/lib/swtpm/:$SNAP/usr/local/lib/
  #     TPMDIR: dir=$SNAP_USER_DATA
  #     CTRL: type=unixio,path=$SNAP_USER_DATA/swtpm-sock

parts:
  python:
    plugin: python
    python-packages:
      - cryptography
  libtpms:
    source: https://github.com/stefanberger/libtpms.git
    plugin: autotools
    source-depth: 1
    autotools-configure-parameters:
      - --with-openssl
      - --with-tpm2
    build-packages:
      - libnss3-dev
      - libssl-dev
      - gawk
      - libtasn1-dev
      - pkg-config
  swtpm:
    after:
      - libtpms
      - python
    source: https://github.com/stefanberger/swtpm.git
    plugin: autotools
    source-depth: 1
    autotools-configure-parameters:
      - --prefix=/usr
      - --with-openssl
    build-packages:
      - libfuse-dev
      - libglib2.0-dev
      - libjson-glib-dev
      - libgmp-dev
      - expect
      - libtasn1-dev
      - tpm-tools
      - gnutls-dev
      - gnutls-bin
      - net-tools
      - socat
      - libseccomp-dev
    stage-packages:
      - libfuse2
    build-environment:
      - CFLAGS: -I$SNAPCRAFT_STAGE/usr/local/include
      - LDFLAGS: -L$SNAPCRAFT_STAGE/usr/local/lib
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/local/lib/pkgconfig/
    stage:
      - -lib64
